/* Landing-page translations — hand-authored marketing copy, not machine
 * output, so each language reads native. Pure data: client-safe.
 *
 * The toggle persists per browser (emLang) and first-visit defaults to the
 * browser language. English is the source of truth: any key missing from a
 * language falls back to EN at the component level. */

export type LangKey = "en" | "es" | "fr" | "de" | "zh";

export const LANG_LABELS: Record<LangKey, string> = {
  en: "English",
  es: "Español",
  fr: "Français",
  de: "Deutsch",
  zh: "中文",
};

export interface LandingCopy {
  nav: { login: string; start: string };
  hero: { eyebrow: string; h1a: string; h1b: string; sub: string; cta: string; note: string };
  stats: { types: string; channels: string; start: string };
  features: { icon: string; title: string; body: string }[];
  show: { eyebrow: string; h2: string; sub: string; cards: { label: string; sub: string }[] };
  price: {
    eyebrow: string; h2: string; sub: string; ribbon: string; perMo: string;
    yearAlt: string; // "{Y}" replaced with the annual price
    tokensMo: string; // "{N}" replaced with the monthly token count
    cta: string; note: string;
    tiers: Record<"STARTER" | "STUDIO" | "ANTHEM", string[]>;
  };
  faq: { eyebrow: string; h2: string; items: { q: string; a: string }[] };
  compare: { eyebrow: string; h2a: string; h2b: string; sub: string; themH: string; usH: string; them: string[]; us: string[] };
  band: { h2: string; p: string; cta: string };
  footer: { copy: string };
  /** The AI trust strip — provider names themselves are proper nouns and
   *  never translated; only the framing copy is. Optional so older language
   *  packs fall back to English until translated. */
  powered?: { eyebrow: string; note: string };
  autopost?: { eyebrow: string; note: string; points: string[] };
}

const EN: LandingCopy = {
  nav: { login: "Log in", start: "Start free" },
  hero: {
    eyebrow: "Marketing on easy mode",
    h1a: "Your whole store's marketing, ",
    h1b: "running itself.",
    sub: "EasyMode turns your products into videos, image ads and SEO articles — then posts them to your socials on a schedule. You approve, it ships. Works with any store.",
    cta: "Start free — 7-day trial",
    note: "Any store, any platform · cancel anytime",
  },
  stats: { types: "ad formats, one subscription", channels: "posting to TikTok, IG & FB", start: "to start" },
  features: [
    { icon: "video", title: "UGC videos that sell", body: "AI presenters hold your product and talk it up — vertical-formatted for TikTok, Reels & Shorts." },
    { icon: "cartoon", title: "Viral-style cartoon ads", body: "Your product in the formats the internet already shares — dream anime, boxed action figure, block build, claymation — or an Anthem your avatar sings on camera." },
    { icon: "seo", title: "SEO articles on autopilot", body: "Buyer-intent articles written for you as ready-to-paste HTML, pulling in free Google traffic month after month." },
    { icon: "post", title: "Auto-posted for you", body: "Every drop goes out to TikTok, Instagram & Facebook on a schedule — captions and hashtags written to travel." },
    { icon: "auto", title: "One-tap autopilot", body: "Pick a goal. EasyMode builds a full month of content, launches it, and scales what works." },
    { icon: "cinema", title: "Cinematic Commercials", body: "A multi-scene story ad with a voice-over and a packshot finale — big-budget TV energy, built from one product photo." },
    { icon: "shield", title: "Product-true, guaranteed", body: "Every ad is quality-checked against your real product photo — wrong artwork, wrong text or wrong size never ships." },
    { icon: "bolt", title: "Click tracking + Boost", body: "Every post carries a tracked link — see which piece earns clicks, then boost the winner in two taps." },
  ],
  show: {
    eyebrow: "Straight from the studio",
    h2: "This is actual EasyMode output.",
    sub: "Not mockups — these covers are generated by the same pipelines that will build your ads.",
    cards: [
      { label: "Avatar AI", sub: "A presenter sells it to camera" },
      { label: "Cartoon Avatar", sub: "8 viral styles, your presenter" },
      { label: "Anthem", sub: "Your avatar sings the ad" },
      { label: "Image ads", sub: "Famous formats, your product" },
      { label: "Product Highlight", sub: "Cinematic motion, no presenter" },
      { label: "Social Proof", sub: "Review cards, written for you" },
      { label: "Viral Post", sub: "Feed-native — doesn't look like an ad" },
    ],
  },
  price: {
    eyebrow: "Pricing",
    h2: "Three plans. Each unlocks more firepower.",
    sub: "Your plan unlocks the generators; monthly tokens meter how much you make. Top up any time.",
    ribbon: "Most popular",
    perMo: "/mo",
    yearAlt: "or ${Y}/yr — 2 months free",
    tokensMo: "{N} tokens / month",
    cta: "Start free →",
    note: "Every plan starts with a 7-day free trial. Cancel anytime — everything you generated stays yours.",
    tiers: {
      STARTER: [
        "AI image ads built on famous ad formats",
        "SEO articles, written for you and ready to paste",
        "Captions + hashtags, auto-posted to TikTok, IG & Facebook",
        "AI product listings & ad copy",
      ],
      STUDIO: [
        "Everything in Starter — plus EVERY video generator",
        "Avatar AI & Product Highlight — presenter or cinematic",
        "Anthem + all 8 Cartoon Avatar styles included",
        "Campaign Autopilot — a month of content, launched for you",
      ],
      ANTHEM: [
        "Every generator, nearly 2× the tokens (1,600/mo)",
        "Best price per generation — built for daily posting",
        "The biggest Campaign Autopilot mixes (Go Viral scale)",
        "Campaign discount on token costs",
      ],
    },
  },
  faq: {
    eyebrow: "Questions",
    h2: "The stuff people ask.",
    items: [
      { q: "How do tokens work?", a: "Your plan unlocks WHICH generators you can use (Starter: images & articles; Studio & Anthem: every generator, video through Anthem). Tokens meter HOW MUCH you generate — every plan refills monthly, and you can top up any time. Tokens never unlock a generator your plan doesn't include." },
      { q: "What does the free trial include?", a: "7 days with every generator unlocked — real videos, cartoon styles, even your Anthem — on a 400-token play budget. Cancel before day 7 and you pay nothing." },
      { q: "What happens if I downgrade?", a: "Everything you already generated stays in your archive, postable forever. Only NEW generation is gated by your current plan." },
      { q: "Is the content labeled as AI?", a: "Yes — every post EasyMode publishes carries the #EasyModeAi tag, keeping your store on the right side of AI-disclosure norms and FTC guidance." },
    ],
  },
  compare: {
    eyebrow: "Coming from another tool?",
    h2a: "Still figuring out ",
    h2b: "Zeely or Arcads?",
    sub: "If you've tried the others, here's why merchants switch to EasyMode.",
    themH: "The usual way",
    usH: "EasyMode",
    them: [
      "A different app for videos, articles, images and posting",
      "You still schedule and post every piece by hand",
      "Per-video pricing that punishes you for growing",
      "Generic AI that doesn't know your catalog",
    ],
    us: [
      "Videos, articles, images & landing pages in one app",
      "Auto-posts to TikTok, Instagram & Facebook on a schedule",
      "One simple token wallet — spend it on anything",
      "Every piece built from your real products",
    ],
  },
  band: {
    h2: "Made for founders who don't have a marketing team.",
    p: "Set it up in a couple of minutes. Wake up to finished content, posted and working.",
    cta: "Get EasyMode",
  },
  footer: { copy: "AI marketing autopilot for your store." },
  powered: { eyebrow: "Powered by frontier AI", note: "We don't borrow a big studio's AI stack — we run one. Every ad is built and quality-checked by frontier models, then approved by you before it ships." },
  autopost: { eyebrow: "Made here. Posted everywhere.", note: "Link your socials once and every approved piece can publish itself — AI caption, per-platform hashtags, and the AI-disclosure tag Meta now requires, handled automatically.", points: ["One-tap posting to TikTok, Instagram & Facebook", "Big-studio output at a budget price — plans from $19/mo", "AI-disclosure compliant captions, so ads don't get rejected"] },
};

const ES: LandingCopy = {
  nav: { login: "Iniciar sesión", start: "Empieza gratis" },
  hero: {
    eyebrow: "Marketing en modo fácil",
    h1a: "Todo el marketing de tu tienda, ",
    h1b: "funcionando solo.",
    sub: "EasyMode convierte tus productos en videos, anuncios de imagen y artículos SEO — y los publica en tus redes según un calendario. Tú apruebas, él publica. Funciona con cualquier tienda.",
    cta: "Empieza gratis — prueba de 7 días",
    note: "Cualquier tienda, cualquier plataforma · cancela cuando quieras",
  },
  stats: { types: "formatos de anuncio, una suscripción", channels: "publicación en TikTok, IG y FB", start: "para empezar" },
  features: [
    { icon: "video", title: "Videos UGC que venden", body: "Presentadores de IA sostienen tu producto y lo presentan — en formato vertical para TikTok, Reels y Shorts." },
    { icon: "cartoon", title: "Anuncios cartoon virales", body: "Tu producto en los formatos que internet ya comparte — anime, figura de colección, bloques, claymation — o un Anthem que tu avatar canta a cámara." },
    { icon: "seo", title: "Artículos SEO en piloto automático", body: "Artículos con intención de compra, escritos para ti en HTML listo para pegar, atrayendo tráfico gratuito de Google mes tras mes." },
    { icon: "post", title: "Publicado por ti", body: "Cada pieza sale a TikTok, Instagram y Facebook según un calendario — con textos y hashtags pensados para viajar." },
    { icon: "auto", title: "Piloto automático en un toque", body: "Elige un objetivo. EasyMode crea un mes entero de contenido, lo lanza y escala lo que funciona." },
    { icon: "cinema", title: "Anuncios cinematográficos", body: "Un anuncio de varias escenas, con voz en off y un plano final del producto — energía de televisión, creado a partir de una sola foto." },
    { icon: "shield", title: "Fiel a tu producto, garantizado", body: "Cada anuncio se contrasta con la foto real de tu producto — nunca se publica con el arte, el texto o el tamaño equivocados." },
    { icon: "bolt", title: "Seguimiento de clics + Boost", body: "Cada publicación lleva un enlace medido — mira qué pieza gana clics y potencia la ganadora en dos toques." },
  ],
  show: {
    eyebrow: "Directo del estudio",
    h2: "Esto es producción real de EasyMode.",
    sub: "No son maquetas — estas portadas las generan los mismos procesos que crearán tus anuncios.",
    cards: [
      { label: "Avatar AI", sub: "Un presentador lo vende a cámara" },
      { label: "Avatar Cartoon", sub: "8 estilos virales, tu presentador" },
      { label: "Anthem", sub: "Tu avatar canta el anuncio" },
      { label: "Anuncios de imagen", sub: "Formatos famosos, tu producto" },
      { label: "Product Highlight", sub: "Movimiento de cine, sin presentador" },
      { label: "Prueba social", sub: "Reseñas y citas, escritas por ti" },
      { label: "Post viral", sub: "Nativo del feed — no parece anuncio" },
    ],
  },
  price: {
    eyebrow: "Precios",
    h2: "Tres planes. Cada uno desbloquea más potencia.",
    sub: "Tu plan desbloquea los generadores; los tokens mensuales miden cuánto creas. Recarga cuando quieras.",
    ribbon: "El más popular",
    perMo: "/mes",
    yearAlt: "o ${Y}/año — 2 meses gratis",
    tokensMo: "{N} tokens / mes",
    cta: "Empieza gratis →",
    note: "Todos los planes empiezan con 7 días de prueba gratis. Cancela cuando quieras — todo lo que generaste es tuyo para siempre.",
    tiers: {
      STARTER: [
        "Anuncios de imagen con IA basados en formatos famosos",
        "Artículos SEO, escritos para ti y listos para pegar",
        "Textos + hashtags, publicados en TikTok, IG y Facebook",
        "Fichas de producto y textos de anuncio con IA",
      ],
      STUDIO: [
        "Todo lo de Starter — más TODOS los generadores de video",
        "Avatar AI y Product Highlight — presentador o cinematográfico",
        "Anthem + los 8 estilos de Avatar Cartoon incluidos",
        "Campaign Autopilot — un mes de contenido, lanzado por ti",
      ],
      ANTHEM: [
        "Todos los generadores, casi el doble de tokens (1.600/mes)",
        "El mejor precio por generación — para publicar a diario",
        "Las campañas más grandes del Autopilot (escala Go Viral)",
        "Descuento de campaña en el costo en tokens",
      ],
    },
  },
  faq: {
    eyebrow: "Preguntas",
    h2: "Lo que todos preguntan.",
    items: [
      { q: "¿Cómo funcionan los tokens?", a: "Tu plan desbloquea QUÉ generadores puedes usar (Starter: imágenes y artículos; Studio y Anthem: todos los generadores). Los tokens miden CUÁNTO generas — cada plan se recarga mensualmente y puedes comprar más cuando quieras. Los tokens nunca desbloquean un generador que tu plan no incluye." },
      { q: "¿Qué incluye la prueba gratis?", a: "7 días con todos los generadores desbloqueados — videos reales, estilos cartoon e incluso tu Anthem — con un presupuesto de 400 tokens. Cancela antes del día 7 y no pagas nada." },
      { q: "¿Qué pasa si bajo de plan?", a: "Todo lo que ya generaste queda en tu archivo, publicable para siempre. Solo la NUEVA generación depende de tu plan actual." },
      { q: "¿El contenido se marca como IA?", a: "Sí — cada publicación de EasyMode lleva la etiqueta #EasyModeAi, manteniendo tu tienda en regla con las normas de divulgación de IA." },
    ],
  },
  compare: {
    eyebrow: "¿Vienes de otra herramienta?",
    h2a: "¿Todavía peleando con ",
    h2b: "Zeely o Arcads?",
    sub: "Si probaste las otras, esto es por lo que los comerciantes se cambian a EasyMode.",
    themH: "Lo de siempre",
    usH: "EasyMode",
    them: [
      "Una app distinta para videos, artículos, imágenes y publicación",
      "Sigues programando y publicando cada pieza a mano",
      "Precio por video que te castiga por crecer",
      "IA genérica que no conoce tu catálogo",
    ],
    us: [
      "Videos, artículos, imágenes y landing pages en una sola app",
      "Publica solo en TikTok, Instagram y Facebook según calendario",
      "Una sola cartera de tokens — gástala en lo que quieras",
      "Cada pieza creada a partir de tus productos reales",
    ],
  },
  band: {
    h2: "Hecho para fundadores sin equipo de marketing.",
    p: "Configúralo en un par de minutos. Despierta con contenido terminado, publicado y funcionando.",
    cta: "Consigue EasyMode",
  },
  footer: { copy: "Piloto automático de marketing con IA para tu tienda." },
  powered: { eyebrow: "Impulsado por IA de frontera", note: "No tomamos prestado el stack de IA de un gran estudio: somos uno. Cada anuncio se crea y verifica con modelos de frontera, y tú lo apruebas antes de publicarse." },
  autopost: { eyebrow: "Creado aquí. Publicado en todas partes.", note: "Conecta tus redes una vez y cada pieza aprobada puede publicarse sola: texto con IA, hashtags por plataforma y la etiqueta de divulgación de IA que Meta exige.", points: ["Publicación con un toque en TikTok, Instagram y Facebook", "Calidad de gran estudio a precio económico — planes desde $19/mes", "Textos conformes con la divulgación de IA, sin anuncios rechazados"] },
};

const FR: LandingCopy = {
  nav: { login: "Connexion", start: "Essai gratuit" },
  hero: {
    eyebrow: "Le marketing en mode facile",
    h1a: "Tout le marketing de votre boutique, ",
    h1b: "en pilote automatique.",
    sub: "EasyMode transforme vos produits en vidéos, visuels publicitaires et articles SEO — puis les publie sur vos réseaux selon un calendrier. Vous validez, il publie. Compatible avec toutes les boutiques.",
    cta: "Essai gratuit — 7 jours",
    note: "Toute boutique, toute plateforme · annulez à tout moment",
  },
  stats: { types: "formats de pub, un seul abonnement", channels: "publication TikTok, IG & FB", start: "pour commencer" },
  features: [
    { icon: "video", title: "Des vidéos UGC qui vendent", body: "Des présentateurs IA tiennent votre produit et en parlent — au format vertical pour TikTok, Reels et Shorts." },
    { icon: "cartoon", title: "Pubs cartoon virales", body: "Votre produit dans les formats que l'internet partage déjà — anime, figurine en boîte, briques, claymation — ou un Anthem que votre avatar chante face caméra." },
    { icon: "seo", title: "Articles SEO en pilote auto", body: "Des articles à intention d'achat, rédigés pour vous en HTML prêt à coller, qui attirent du trafic Google gratuit mois après mois." },
    { icon: "post", title: "Publication automatique", body: "Chaque création part sur TikTok, Instagram et Facebook selon un calendrier — légendes et hashtags pensés pour voyager." },
    { icon: "auto", title: "Pilote auto en un geste", body: "Choisissez un objectif. EasyMode crée un mois entier de contenu, le lance et amplifie ce qui marche." },
    { icon: "cinema", title: "Publicités cinématographiques", body: "Une publicité en plusieurs scènes, avec voix off et plan produit final — une énergie de télévision, créée à partir d'une seule photo." },
    { icon: "shield", title: "Fidèle à votre produit, garanti", body: "Chaque publicité est vérifiée face à la vraie photo de votre produit — jamais de visuel, de texte ou de taille erronés." },
    { icon: "bolt", title: "Suivi des clics + Boost", body: "Chaque publication porte un lien tracké — voyez ce qui génère des clics, puis boostez le gagnant en deux gestes." },
  ],
  show: {
    eyebrow: "Tout droit sorti du studio",
    h2: "Voici de vraies créations EasyMode.",
    sub: "Pas des maquettes — ces visuels sont générés par les mêmes pipelines qui créeront vos publicités.",
    cards: [
      { label: "Avatar AI", sub: "Un présentateur vend face caméra" },
      { label: "Avatar Cartoon", sub: "8 styles viraux, votre présentateur" },
      { label: "Anthem", sub: "Votre avatar chante la pub" },
      { label: "Visuels publicitaires", sub: "Formats célèbres, votre produit" },
      { label: "Product Highlight", sub: "Mouvement cinéma, sans présentateur" },
      { label: "Preuve sociale", sub: "Cartes d'avis, écrites pour vous" },
      { label: "Post viral", sub: "Natif du feed — ne ressemble pas à une pub" },
    ],
  },
  price: {
    eyebrow: "Tarifs",
    h2: "Trois formules. Chacune débloque plus de puissance.",
    sub: "Votre formule débloque les générateurs ; les tokens mensuels mesurent votre volume. Rechargez à tout moment.",
    ribbon: "Le plus populaire",
    perMo: "/mois",
    yearAlt: "ou {Y} $/an — 2 mois offerts",
    tokensMo: "{N} tokens / mois",
    cta: "Essai gratuit →",
    note: "Chaque formule commence par 7 jours d'essai gratuit. Annulez à tout moment — tout ce que vous avez généré reste à vous.",
    tiers: {
      STARTER: [
        "Visuels publicitaires IA inspirés des formats célèbres",
        "Articles SEO, rédigés pour vous et prêts à coller",
        "Légendes + hashtags, auto-publiés sur TikTok, IG et Facebook",
        "Fiches produit et textes publicitaires IA",
      ],
      STUDIO: [
        "Tout Starter — plus TOUS les générateurs vidéo",
        "Avatar AI et Product Highlight — présentateur ou cinématique",
        "Anthem + les 8 styles d'Avatar Cartoon inclus",
        "Campaign Autopilot — un mois de contenu, lancé pour vous",
      ],
      ANTHEM: [
        "Tous les générateurs, presque 2× plus de tokens (1 600/mois)",
        "Le meilleur prix par génération — pensé pour publier chaque jour",
        "Les plus grandes campagnes de l'Autopilot (échelle Go Viral)",
        "Remise campagne sur le coût en tokens",
      ],
    },
  },
  faq: {
    eyebrow: "Questions",
    h2: "Ce qu'on nous demande.",
    items: [
      { q: "Comment fonctionnent les tokens ?", a: "Votre formule débloque QUELS générateurs vous pouvez utiliser (Starter : images et articles ; Studio et Anthem : tous les générateurs). Les tokens mesurent COMBIEN vous générez — chaque formule se recharge tous les mois, et vous pouvez en acheter à tout moment. Les tokens ne débloquent jamais un générateur absent de votre formule." },
      { q: "Que comprend l'essai gratuit ?", a: "7 jours avec tous les générateurs débloqués — vraies vidéos, styles cartoon et même votre Anthem — avec un budget de 400 tokens. Annulez avant le 7e jour et vous ne payez rien." },
      { q: "Que se passe-t-il si je rétrograde ?", a: "Tout ce que vous avez déjà généré reste dans vos archives, publiable pour toujours. Seule la NOUVELLE génération dépend de votre formule actuelle." },
      { q: "Le contenu est-il signalé comme IA ?", a: "Oui — chaque publication d'EasyMode porte le tag #EasyModeAi, gardant votre boutique en règle avec les normes de transparence sur l'IA." },
    ],
  },
  compare: {
    eyebrow: "Vous venez d'un autre outil ?",
    h2a: "Toujours aux prises avec ",
    h2b: "Zeely ou Arcads ?",
    sub: "Si vous avez essayé les autres, voici pourquoi les marchands passent à EasyMode.",
    themH: "La méthode habituelle",
    usH: "EasyMode",
    them: [
      "Une app différente pour vidéos, articles, images et publication",
      "Vous programmez et publiez encore chaque pièce à la main",
      "Un prix à la vidéo qui vous punit de grandir",
      "Une IA générique qui ne connaît pas votre catalogue",
    ],
    us: [
      "Vidéos, articles, images et landing pages dans une seule app",
      "Publication auto sur TikTok, Instagram et Facebook",
      "Un seul portefeuille de tokens — à dépenser librement",
      "Chaque pièce créée à partir de vos vrais produits",
    ],
  },
  band: {
    h2: "Conçu pour les fondateurs sans équipe marketing.",
    p: "Installez-le en deux minutes. Réveillez-vous avec du contenu fini, publié et qui travaille.",
    cta: "Adopter EasyMode",
  },
  footer: { copy: "Le pilote automatique marketing IA de votre boutique." },
  powered: { eyebrow: "Propulsé par une IA de pointe", note: "Nous n'empruntons pas la stack IA d'un grand studio — nous en sommes un. Chaque publicité est créée et contrôlée par des modèles de pointe, puis validée par vous avant diffusion." },
  autopost: { eyebrow: "Créé ici. Publié partout.", note: "Connectez vos réseaux une fois : chaque création approuvée peut se publier seule — légende IA, hashtags par plateforme et mention de divulgation IA exigée par Meta.", points: ["Publication en un geste sur TikTok, Instagram et Facebook", "Qualité grand studio à petit prix — dès 19 $/mois", "Légendes conformes à la divulgation IA, zéro pub rejetée"] },
};

const DE: LandingCopy = {
  nav: { login: "Anmelden", start: "Kostenlos starten" },
  hero: {
    eyebrow: "Marketing im Easy Mode",
    h1a: "Das komplette Marketing deines Shops, ",
    h1b: "läuft von selbst.",
    sub: "EasyMode verwandelt deine Produkte in Videos, Werbebilder und SEO-Artikel — und postet sie nach Zeitplan auf deinen Kanälen. Du gibst frei, es liefert. Funktioniert mit jedem Shop.",
    cta: "Kostenlos starten — 7 Tage testen",
    note: "Jeder Shop, jede Plattform · jederzeit kündbar",
  },
  stats: { types: "Anzeigenformate, ein Abo", channels: "Posting auf TikTok, IG & FB", start: "zum Start" },
  features: [
    { icon: "video", title: "UGC-Videos, die verkaufen", body: "KI-Presenter halten dein Produkt in der Hand und stellen es vor — vertikal formatiert für TikTok, Reels & Shorts." },
    { icon: "cartoon", title: "Virale Cartoon-Ads", body: "Dein Produkt in den Formaten, die das Internet schon teilt — Anime, Sammelfigur, Klötzchen-Look, Knetanimation — oder ein Anthem, das dein Avatar vor der Kamera singt." },
    { icon: "seo", title: "SEO-Artikel auf Autopilot", body: "Kaufintention-Artikel, für dich als fertiges HTML zum Einfügen geschrieben — kostenloser Google-Traffic, Monat für Monat." },
    { icon: "post", title: "Automatisch gepostet", body: "Jeder Drop geht nach Zeitplan auf TikTok, Instagram & Facebook — mit Captions und Hashtags, die reisen." },
    { icon: "auto", title: "Autopilot mit einem Tipp", body: "Wähle ein Ziel. EasyMode baut einen ganzen Content-Monat, startet ihn und skaliert, was funktioniert." },
    { icon: "cinema", title: "Kinoreife Werbespots", body: "Ein Werbespot mit mehreren Szenen, Voice-over und Produkt-Finale — Fernseh-Energie, aus einem einzigen Produktfoto." },
    { icon: "shield", title: "Produkttreu, garantiert", body: "Jede Anzeige wird gegen dein echtes Produktfoto geprüft — falsches Motiv, falscher Text oder falsche Größe gehen nie raus." },
    { icon: "bolt", title: "Klick-Tracking + Boost", body: "Jeder Post trägt einen getrackten Link — sieh, was Klicks bringt, und booste den Gewinner mit zwei Taps." },
  ],
  show: {
    eyebrow: "Direkt aus dem Studio",
    h2: "Das ist echter EasyMode-Output.",
    sub: "Keine Mockups — diese Cover erzeugen dieselben Pipelines, die auch deine Ads bauen werden.",
    cards: [
      { label: "Avatar AI", sub: "Ein Presenter verkauft in die Kamera" },
      { label: "Cartoon Avatar", sub: "8 virale Styles, dein Presenter" },
      { label: "Anthem", sub: "Dein Avatar singt die Werbung" },
      { label: "Werbebilder", sub: "Berühmte Formate, dein Produkt" },
      { label: "Product Highlight", sub: "Kino-Bewegung, ohne Presenter" },
      { label: "Social Proof", sub: "Bewertungskarten, automatisch getextet" },
      { label: "Viraler Post", sub: "Feed-nativ — wirkt nicht wie Werbung" },
    ],
  },
  price: {
    eyebrow: "Preise",
    h2: "Drei Pläne. Jeder schaltet mehr Feuerkraft frei.",
    sub: "Dein Plan schaltet die Generatoren frei; monatliche Tokens messen die Menge. Jederzeit aufladbar.",
    ribbon: "Am beliebtesten",
    perMo: "/Monat",
    yearAlt: "oder {Y} $/Jahr — 2 Monate geschenkt",
    tokensMo: "{N} Tokens / Monat",
    cta: "Kostenlos starten →",
    note: "Jeder Plan beginnt mit 7 Tagen Gratis-Test. Jederzeit kündbar — alles, was du erzeugt hast, bleibt deins.",
    tiers: {
      STARTER: [
        "KI-Werbebilder nach berühmten Ad-Formaten",
        "SEO-Artikel, für dich geschrieben & bereit zum Einfügen",
        "Captions + Hashtags, automatisch auf TikTok, IG & Facebook",
        "KI-Produkttexte & Anzeigentexte",
      ],
      STUDIO: [
        "Alles aus Starter — plus JEDER Video-Generator",
        "Avatar AI & Product Highlight — Presenter oder filmisch",
        "Anthem + alle 8 Cartoon-Avatar-Styles inklusive",
        "Campaign Autopilot — ein Content-Monat, für dich gestartet",
      ],
      ANTHEM: [
        "Jeder Generator, fast 2× so viele Tokens (1.600/Monat)",
        "Bester Preis pro Generierung — gemacht für tägliches Posten",
        "Die größten Autopilot-Kampagnen (Go-Viral-Maßstab)",
        "Kampagnen-Rabatt auf Token-Kosten",
      ],
    },
  },
  faq: {
    eyebrow: "Fragen",
    h2: "Was alle wissen wollen.",
    items: [
      { q: "Wie funktionieren Tokens?", a: "Dein Plan schaltet frei, WELCHE Generatoren du nutzen kannst (Starter: Bilder & Artikel; Studio & Anthem: alle Generatoren). Tokens messen, WIE VIEL du erzeugst — jeder Plan lädt monatlich auf, und du kannst jederzeit nachkaufen. Tokens schalten nie einen Generator frei, den dein Plan nicht enthält." },
      { q: "Was ist im Gratis-Test enthalten?", a: "7 Tage mit allen Generatoren freigeschaltet — echte Videos, Cartoon-Styles und sogar dein Anthem — mit 400 Tokens Spielbudget. Kündige vor Tag 7 und zahlst nichts." },
      { q: "Was passiert beim Downgrade?", a: "Alles bereits Erzeugte bleibt in deinem Archiv, für immer postbar. Nur NEUE Generierungen richten sich nach deinem aktuellen Plan." },
      { q: "Wird der Content als KI gekennzeichnet?", a: "Ja — jeder Post von EasyMode trägt den Tag #EasyModeAi und hält deinen Shop damit konform mit KI-Kennzeichnungsnormen." },
    ],
  },
  compare: {
    eyebrow: "Du kommst von einem anderen Tool?",
    h2a: "Kämpfst du noch mit ",
    h2b: "Zeely oder Arcads?",
    sub: "Wer die anderen probiert hat — darum wechseln Händler zu EasyMode.",
    themH: "Der übliche Weg",
    usH: "EasyMode",
    them: [
      "Eine andere App für Videos, Artikel, Bilder und Posting",
      "Du planst und postest immer noch jedes Stück von Hand",
      "Preis pro Video, der Wachstum bestraft",
      "Generische KI, die deinen Katalog nicht kennt",
    ],
    us: [
      "Videos, Artikel, Bilder & Landing Pages in einer App",
      "Auto-Posting auf TikTok, Instagram & Facebook nach Zeitplan",
      "Eine einzige Token-Wallet — für alles einsetzbar",
      "Jedes Stück gebaut aus deinen echten Produkten",
    ],
  },
  band: {
    h2: "Gemacht für Gründer ohne Marketing-Team.",
    p: "In wenigen Minuten eingerichtet. Wach auf zu fertigem Content — gepostet und am Arbeiten.",
    cta: "EasyMode holen",
  },
  footer: { copy: "KI-Marketing-Autopilot für deinen Shop." },
  powered: { eyebrow: "Angetrieben von Frontier-KI", note: "Wir leihen uns keinen Studio-KI-Stack — wir sind das Studio. Jede Anzeige wird von Frontier-Modellen erstellt und geprüft, und geht erst nach deiner Freigabe live." },
  autopost: { eyebrow: "Hier erstellt. Überall gepostet.", note: "Einmal verbinden — jedes freigegebene Stück postet sich selbst: KI-Caption, Hashtags pro Plattform und die von Meta geforderte KI-Kennzeichnung inklusive.", points: ["Ein-Tipp-Posting auf TikTok, Instagram & Facebook", "Studio-Qualität zum Budget-Preis — Pläne ab 19 $/Monat", "KI-Kennzeichnung automatisch — keine abgelehnten Anzeigen"] },
};

const ZH: LandingCopy = {
  nav: { login: "登录", start: "免费开始" },
  hero: {
    eyebrow: "轻松模式营销",
    h1a: "让你店铺的全部营销，",
    h1b: "自动运转。",
    sub: "EasyMode 把你的产品变成视频、广告图和 SEO 文章 — 并按排期自动发布到你的社交账号。你来审核，它来发布。适用于任何店铺。",
    cta: "免费开始 — 7 天试用",
    note: "任何店铺、任何平台 · 随时取消",
  },
  stats: { types: "种广告形式，一份订阅", channels: "键发布到 TikTok、IG 和 FB", start: "起步价" },
  features: [
    { icon: "video", title: "能带货的 UGC 视频", body: "AI 主播手持你的产品进行讲解 — 竖屏格式，适配 TikTok、Reels 和 Shorts。" },
    { icon: "cartoon", title: "病毒式卡通广告", body: "把你的产品做成全网疯传的风格 — 梦幻动漫、盒装手办、方块世界、黏土动画 — 或者让你的头像出镜演唱产品主题曲 Anthem。" },
    { icon: "seo", title: "SEO 文章全自动", body: "面向购买意图的文章，自动撰写并发布，月复一月为你带来免费的 Google 流量。" },
    { icon: "post", title: "自动发布", body: "每条内容按排期发布到 TikTok、Instagram 和 Facebook — 文案和标签都为传播而写。" },
    { icon: "auto", title: "一键自动驾驶", body: "选一个目标，EasyMode 生成整月内容，自动发布，并放大有效的部分。" },
    { icon: "cinema", title: "电影级广告片", body: "多场景故事广告，配旁白与产品定格收尾 — 只用一张产品图，做出电视广告的质感。" },
    { icon: "shield", title: "忠于产品，有保障", body: "每条广告都会与你的真实产品图核对 — 画错、写错、尺寸错的内容永远不会发布。" },
    { icon: "bolt", title: "点击追踪 + 加投", body: "每条内容都带追踪链接 — 看清哪条带来点击，两步加投赢家。" },
  ],
  show: {
    eyebrow: "工作室直出",
    h2: "这些是 EasyMode 的真实作品。",
    sub: "不是效果图 — 这些封面由将为你制作广告的同一套流水线生成。",
    cards: [
      { label: "Avatar AI", sub: "主播对镜头带货" },
      { label: "卡通头像", sub: "8 种病毒风格，你的主播" },
      { label: "Anthem", sub: "你的头像唱出广告" },
      { label: "广告图", sub: "经典版式，你的产品" },
      { label: "产品大片", sub: "电影级运镜，无需主播" },
      { label: "口碑卡片", sub: "评价与引述，自动生成" },
      { label: "爆款帖子", sub: "融入信息流，不像广告" },
    ],
  },
  price: {
    eyebrow: "价格",
    h2: "三档套餐，逐级解锁更强火力。",
    sub: "套餐决定你能用哪些生成器；每月代币决定你能生成多少。随时可以充值。",
    ribbon: "最受欢迎",
    perMo: "/月",
    yearAlt: "或 {Y} 美元/年 — 免费送 2 个月",
    tokensMo: "每月 {N} 代币",
    cta: "免费开始 →",
    note: "每个套餐都含 7 天免费试用。随时取消 — 你生成的所有内容永远归你。",
    tiers: {
      STARTER: [
        "基于经典广告版式的 AI 广告图",
        "SEO 文章，自动撰写并发布",
        "文案 + 标签，自动发布到 TikTok、IG 和 Facebook",
        "AI 产品文案与广告文案",
      ],
      STUDIO: [
        "包含 Starter 全部功能 — 并解锁所有视频生成器",
        "Avatar AI 与 Product Highlight — 主播或电影感",
        "Anthem 主题曲 + 全部 8 种卡通头像风格",
        "Campaign Autopilot — 整月内容，自动投放",
      ],
      ANTHEM: [
        "全部生成器，代币近 2 倍（每月 1,600）",
        "单次生成最划算 — 适合每日发布",
        "最大规模的 Autopilot 营销活动（Go Viral 级）",
        "营销活动代币费用折扣",
      ],
    },
  },
  faq: {
    eyebrow: "常见问题",
    h2: "大家常问的。",
    items: [
      { q: "代币是怎么用的？", a: "套餐决定你能用哪些生成器（Starter：图片和文章；Studio 与 Anthem：全部生成器）。代币决定你能生成多少 — 每月自动补充，也可随时充值。代币永远不能解锁套餐之外的生成器。" },
      { q: "免费试用包含什么？", a: "7 天全部生成器解锁 — 真正的视频、卡通风格、甚至你的 Anthem — 附 400 代币体验额度。第 7 天前取消则分文不付。" },
      { q: "降级会怎样？", a: "你已生成的所有内容都保留在档案库里，永远可以发布。只有新的生成受当前套餐限制。" },
      { q: "内容会标注为 AI 吗？", a: "会 — EasyMode 发布的每条内容都带 #EasyModeAi 标签，让你的店铺符合 AI 披露规范。" },
    ],
  },
  compare: {
    eyebrow: "从其他工具转来？",
    h2a: "还在折腾 ",
    h2b: "Zeely 或 Arcads？",
    sub: "如果你用过其他工具，这就是商家改用 EasyMode 的原因。",
    themH: "老办法",
    usH: "EasyMode",
    them: [
      "视频、文章、图片、发布各用一个应用",
      "每条内容仍要手动排期和发布",
      "按视频计费，越成长越贵",
      "通用 AI，不了解你的商品目录",
    ],
    us: [
      "视频、文章、图片和落地页，一个应用全搞定",
      "按排期自动发布到 TikTok、Instagram 和 Facebook",
      "一个代币钱包 — 想怎么花就怎么花",
      "每条内容都基于你的真实产品",
    ],
  },
  band: {
    h2: "为没有营销团队的创始人而生。",
    p: "几分钟完成设置。一觉醒来，内容已做好、已发布、正在起效。",
    cta: "获取 EasyMode",
  },
  footer: { copy: "你店铺的 AI 营销自动驾驶。" },
  powered: { eyebrow: "由前沿 AI 驱动", note: "我们不是在借用大工作室的 AI——我们就是那个工作室。每条广告由前沿模型生成并质检，发布前由你亲自审核。" },
  autopost: { eyebrow: "在这里创作，发布到所有平台", note: "只需绑定一次社交账号，每条通过审核的内容都能自动发布——AI 文案、平台专属话题标签，以及 Meta 要求的 AI 声明标签，全部自动处理。", points: ["一键发布到 TikTok、Instagram 和 Facebook", "大工作室品质，预算价格——每月 $19 起", "AI 声明合规文案，广告不再被拒"] },
};

export const LANDING_I18N: Record<LangKey, LandingCopy> = { en: EN, es: ES, fr: FR, de: DE, zh: ZH };

export function detectLang(): LangKey {
  try {
    const saved = localStorage.getItem("emLang") as LangKey | null;
    if (saved && LANDING_I18N[saved]) return saved;
    const nav = (navigator.language || "en").toLowerCase();
    if (nav.startsWith("es")) return "es";
    if (nav.startsWith("fr")) return "fr";
    if (nav.startsWith("de")) return "de";
    if (nav.startsWith("zh")) return "zh";
  } catch { /* SSR / privacy mode */ }
  return "en";
}
