import { json, redirect, type LoaderFunctionArgs } from "@remix-run/node";
import { useLoaderData } from "@remix-run/react";
import { useEffect, useState } from "react";
import { PLAN_TIERS, annualPrice, planCapacityLine } from "../lib/plan-config";
import { LANDING_I18N, LANG_LABELS, detectLang, type LangKey } from "../lib/landing-i18n";

export const loader = async ({ request }: LoaderFunctionArgs) => {
  const url = new URL(request.url);

  // Embedded / install traffic always carries a shop param → send to the
  // embedded app area (/app), which performs the App Bridge token exchange.
  // (Redirecting to /auth here breaks fresh installs — it returns null.)
  if (url.searchParams.get("shop")) {
    throw redirect(`/app?${url.searchParams.toString()}`);
  }

  // No shop param → the public marketing page (also serves as the health check).
  return json({ ok: true });
};

export default function Index() {
  useLoaderData<typeof loader>();
  // Language toggle — persisted per browser, auto-detected on first visit.
  const [lang, setLang] = useState<LangKey>("en");
  useEffect(() => { setLang(detectLang()); }, []);
  useEffect(() => { try { document.documentElement.lang = lang; } catch { /* SSR */ } }, [lang]);
  const pick = (l: LangKey) => { setLang(l); try { localStorage.setItem("emLang", l); } catch { /* private mode */ } };
  const t = LANDING_I18N[lang] || LANDING_I18N.en;

  return (
    <>
      <style dangerouslySetInnerHTML={{ __html: CSS }} />
      <div className="lz">
        <header className="lz-nav">
          <div className="lz-brand">
            <span className="lz-crest" style={{ width: 34, height: 34 }} aria-hidden="true">
              <img src="/easymode-head.png?v=2" alt="" />
            </span>
            <span>Easy<b>Mode</b></span>
          </div>
          <div style={{ display: "flex", gap: 10, alignItems: "center" }}>
            <label className="lz-lang">
              🌐
              <select value={lang} onChange={(e) => pick(e.target.value as LangKey)} aria-label="Language">
                {(Object.keys(LANG_LABELS) as LangKey[]).map((l) => (
                  <option key={l} value={l}>{LANG_LABELS[l]}</option>
                ))}
              </select>
            </label>
            <a className="lz-navlink" href="/web/login">{t.nav.login}</a>
            <a className="lz-navcta" href="/web/signup">{t.nav.start}</a>
          </div>
        </header>

        <main className="lz-hero">
          <span className="lz-rose lz-rose-hero" aria-hidden="true" />
          <span className="lz-eyebrow">{t.hero.eyebrow}</span>
          <h1>{t.hero.h1a}<span className="lz-grad">{t.hero.h1b}</span></h1>
          <p className="lz-sub">{t.hero.sub}</p>
          <div className="lz-ctas">
            <a className="lz-cta" href="/web/signup"><span className="lz-arr-w">{t.hero.cta}<span className="lz-arr">→</span></span></a>
            <span className="lz-note">{t.hero.note}</span>
          </div>

          {/* THE PROOF, ABOVE THE FOLD. A real EasyMode commercial — made by
              the same pipeline a merchant gets — playing before a single
              claim is read. The pitch is the output. */}
          <div className="lz-heroshow">
            <div className="lz-herorow">
              {/* Desktop-only wings — one phone alone on a wide stage read as
                  a stand-in. Two more formats flank it: an avatar presenter
                  and a cinematic product highlight, both muted loops. */}
              <video
                className="lz-flank"
                src="/showcase/flank-left.mp4?v=1"
                poster="/showcase/flank-left.jpg?v=1"
                autoPlay muted loop playsInline
                aria-label="An EasyMode avatar presenter ad"
              />
              <video
                className="lz-herovid"
                src="/showcase/commercial.mp4?v=2"
                poster="/showcase/commercial-cover.jpg?v=2"
                autoPlay muted loop playsInline
                aria-label="A cinematic commercial generated by EasyMode"
              />
              <video
                className="lz-flank"
                src="/showcase/flank-right.mp4?v=1"
                poster="/showcase/flank-right.jpg?v=1"
                autoPlay muted loop playsInline
                aria-label="An EasyMode cinematic product highlight"
              />
            </div>
            <span className="lz-herotag">▶ Real output — generated &amp; voiced by EasyMode</span>
          </div>

          <div className="lz-stats">
            <div><b>9</b><span>{t.stats.types}</span></div>
            <div className="lz-div" />
            <div><b>1-tap</b><span>{t.stats.channels}</span></div>
            <div className="lz-div" />
            <div><b>$19</b><span>{t.stats.start}</span></div>
          </div>
        </main>

        {/* AI trust strip — the engines behind the output, named openly with
            their official brand glyphs (Simple Icons set) so merchants know
            exactly what's building their ads. Greyscale until hover, then
            true brand colour. */}
        <section className="lz-powered" aria-label="AI technology powering EasyMode">
          <span className="lz-eyebrow">{(t.powered || LANDING_I18N.en.powered!).eyebrow}</span>
          <div className="lz-pow-row">
            <span className="lz-pow"><img src="/ai-logos/claude.svg" alt="Claude logo" /><b>Claude</b><i>Anthropic</i></span>
            <span className="lz-pow"><img src="/ai-logos/deepmind.svg" alt="Google DeepMind logo" /><b>Nano&nbsp;Banana</b><i>Google DeepMind</i></span>
            <span className="lz-pow"><img src="/ai-logos/bytedance.svg" alt="ByteDance logo" /><b>Seedream</b><i>ByteDance</i></span>
            <span className="lz-pow"><img src="/ai-logos/kuaishou.svg" alt="Kuaishou logo" /><b>Kling&nbsp;AI</b><i>Kuaishou</i></span>
            <span className="lz-pow"><img src="/ai-logos/minimax.svg" alt="MiniMax logo" /><b>MiniMax</b><i>Speech&nbsp;&amp;&nbsp;Voice</i></span>
          </div>
          <p className="lz-pow-note">{(t.powered || LANDING_I18N.en.powered!).note}</p>
        </section>

        {/* Auto-posting strip — the pipeline doesn't stop at "here's your
            ad": it posts it. Same visual language as the AI strip above so
            the two read as one trust system. */}
        <section className="lz-autopost" aria-label="Automatic posting to social platforms">
          <span className="lz-eyebrow">{(t.autopost || LANDING_I18N.en.autopost!).eyebrow}</span>
          <div className="lz-pow-row">
            <span className="lz-pow"><img src="/ai-logos/tiktok.svg" alt="TikTok logo" /><b>TikTok</b></span>
            <span className="lz-pow"><img src="/ai-logos/instagram.svg" alt="Instagram logo" /><b>Instagram</b></span>
            <span className="lz-pow"><img src="/ai-logos/facebook.svg" alt="Facebook logo" /><b>Facebook</b></span>
          </div>
          <ul className="lz-ap-points">
            {(t.autopost || LANDING_I18N.en.autopost!).points.map((p) => (
              <li key={p}>{p}</li>
            ))}
          </ul>
          <p className="lz-pow-note">{(t.autopost || LANDING_I18N.en.autopost!).note}</p>
        </section>

        <section className="lz-feats"><span className="lz-rose lz-rose-feats" aria-hidden="true" />
          {t.features.map((f) => (
            <div className="lz-card" key={f.title}>
              <div className="lz-ic">{f.icon}</div>
              <h3>{f.title}</h3>
              <p>{f.body}</p>
            </div>
          ))}
        </section>

        {/* Real output — these are the SAME live renders the app serves its
            pickers from (they self-forge on this server; no mock art). */}
        <section className="lz-show"><span className="lz-rose lz-rose-show" aria-hidden="true" />
          <span className="lz-eyebrow">{t.show.eyebrow}</span>
          <h2>{t.show.h2}</h2>
          <p className="lz-show-sub">{t.show.sub}</p>
          <div className="lz-show-grid">
            <figure className="lz-show-card" key="commercial">
              <video className="lz-show-vid" src="/showcase/commercial.mp4?v=2" poster="/showcase/commercial-cover.jpg?v=2" autoPlay muted loop playsInline aria-label="EasyMode-generated commercial" />
              <figcaption><b>Commercial</b><span>A cinematic story ad — script, scenes &amp; voice by EasyMode</span></figcaption>
            </figure>
            {[
              "/style-tiles/avatarcover.jpg?v=4",
              "/style-tiles/cover.jpg?v=4",
              "/style-tiles/anthemcover.jpg?v=4",
              "/ad-templates/format-magazine.jpg?v=1",
              "/ad-templates/phcover.jpg?v=1",
              "/ad-templates/format-review.jpg?v=1",
              "/ad-templates/format-tweet.jpg?v=1",
            ].map((src, i) => (
              <figure className="lz-show-card" key={src}>
                <span className="lz-show-img" style={{ backgroundImage: `url(${src})` }} />
                <figcaption><b>{t.show.cards[i]?.label}</b><span>{t.show.cards[i]?.sub}</span></figcaption>
              </figure>
            ))}
          </div>
        </section>

        {/* Pricing — rendered from the SAME plan-config the app bills from,
            so the public page can never drift from the real ladder. */}
        <section className="lz-price" id="pricing">
          <span className="lz-eyebrow">{t.price.eyebrow}</span>
          <h2>{t.price.h2}</h2>
          <p className="lz-show-sub">{t.price.sub}</p>
          <div className="lz-price-grid">
            {PLAN_TIERS.map((tier) => (
              <div className={`lz-price-card${tier.highlight ? " feat" : ""}`} key={tier.key}>
                {tier.highlight && <span className="lz-price-ribbon">{t.price.ribbon}</span>}
                <div className="lz-price-name">{tier.name}</div>
                <div className="lz-price-amt">${tier.price}<small>{t.price.perMo}</small></div>
                <div className="lz-price-alt">{t.price.yearAlt.replace("{Y}", annualPrice(tier).toLocaleString())}</div>
                <div className="lz-price-tok">{t.price.tokensMo.replace("{N}", tier.monthlyTokens.toLocaleString())}</div>
                {lang === "en" && <div className="lz-price-cap">{planCapacityLine(tier)}</div>}
                <ul>{(t.price.tiers[tier.key] || tier.features).map((f) => <li key={f}>{f}</li>)}</ul>
                <a className="lz-price-cta" href="/web/signup">{t.price.cta}</a>
              </div>
            ))}
          </div>
          <div className="lz-price-note">{t.price.note}</div>
        </section>

        <section className="lz-faq">
          <span className="lz-eyebrow">{t.faq.eyebrow}</span>
          <h2>{t.faq.h2}</h2>
          <div className="lz-faq-list">
            {t.faq.items.map((f) => (
              <details key={f.q}>
                <summary>{f.q}</summary>
                <p>{f.a}</p>
              </details>
            ))}
          </div>
        </section>

        <section className="lz-compare">
          <span className="lz-eyebrow">{t.compare.eyebrow}</span>
          <h2>{t.compare.h2a}<span className="lz-vsname">{t.compare.h2b}</span></h2>
          <p className="lz-compare-sub">{t.compare.sub}</p>
          <div className="lz-vs">
            <div className="lz-vs-col them">
              <div className="lz-vs-h">{t.compare.themH}</div>
              <ul>{t.compare.them.map((l) => <li key={l}>{l}</li>)}</ul>
            </div>
            <div className="lz-vs-col us">
              <span className="lz-rose lz-rose-vs" aria-hidden="true" />
              <div className="lz-vs-h">{t.compare.usH}</div>
              <ul>{t.compare.us.map((l) => <li key={l}>{l}</li>)}</ul>
            </div>
          </div>
        </section>

        <section className="lz-band">
          <div className="lz-band-in">
            <span className="lz-rose lz-rose-band" aria-hidden="true" />
            <h2>{t.band.h2}</h2>
            <p>{t.band.p}</p>
            <a className="lz-cta gold" href="/web/signup"><span className="lz-arr-w">{t.band.cta}<span className="lz-arr">→</span></span></a>
          </div>
        </section>

        <footer className="lz-foot">
          <div className="lz-brand small">
            <span className="lz-crest" style={{ width: 26, height: 26 }} aria-hidden="true">
              <img src="/easymode-head.png?v=2" alt="" />
            </span>
            <span>Easy<b>Mode</b><i>.io</i></span>
          </div>
          <span className="lz-copy">{t.footer.copy}</span>
          <nav className="lz-footlinks" aria-label="Footer">
            <a href="#pricing">Pricing</a>
            <a href="/privacy">Privacy</a>
            <a href="/terms">Terms</a>
            <a href="mailto:hello@easymodeapp.com">Contact</a>
            <a href="mailto:partners@easymodeapp.com?subject=Affiliate%20program">Affiliates</a>
          </nav>
        </footer>
      </div>
    </>
  );
}

const CSS = `
@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@600;700;800&family=Inter:wght@400;500;600&display=swap");
*{box-sizing:border-box}
html,body{margin:0;padding:0}
.lz{--paper:#F4F1E6;--card:#FDFCF7;--ink:#14201A;--ink2:#4A554E;--line:#E4DFCF;
  --green:#0C7A46;--green2:#0F9152;--green-deep:#0A3D26;--gold:#B08526;--gold-hi:#E7C879;--gold-deep:#7E5E13;--mint:#7FE0AC;
  position:relative;min-height:100vh;color:var(--ink);font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;overflow-x:hidden;
  background:
    radial-gradient(60% 45% at 50% -5%,rgba(15,145,82,.13),transparent 60%),
    radial-gradient(50% 40% at 92% 4%,rgba(176,133,38,.10),transparent 60%),
    radial-gradient(46% 34% at 4% 46%,rgba(12,122,70,.075),transparent 66%),
    var(--paper);}
.lz-nav{display:flex;align-items:center;justify-content:space-between;max-width:1080px;margin:0 auto;padding:22px 26px;}
.lz-brand{display:flex;align-items:center;gap:9px;font-family:Poppins,sans-serif;font-weight:800;font-size:19px;letter-spacing:-.01em;color:var(--ink);}
.lz-brand b{color:var(--gold);font-weight:800}
.lz-brand i{color:var(--gold);font-style:normal;font-size:.7em;opacity:.8}
.lz-brand.small{font-size:15px;opacity:.9}
.lz-navcta{font-family:Poppins,sans-serif;font-weight:800;font-size:13px;color:#fff;text-decoration:none;padding:10px 18px;border-radius:11px;
  background:linear-gradient(165deg,#12A85E,#0B6B3E);box-shadow:0 5px 14px rgba(12,122,70,.28);transition:filter .12s;}
.lz-navlink{font-weight:700;font-size:13px;color:var(--ink2);text-decoration:none;}
.lz-navlink:hover{color:var(--ink)}
.lz-lang{display:inline-flex;align-items:center;gap:5px;font-size:14px;}
.lz-lang select{border:1px solid var(--line);background:var(--card);color:var(--ink);border-radius:9px;
  padding:6px 8px;font:inherit;font-size:12.5px;font-weight:600;cursor:pointer;}
.lz-alt{color:var(--green);font-weight:600;}
.lz-navcta:hover{filter:brightness(1.05)}
.lz-hero{max-width:820px;margin:0 auto;padding:52px 26px 30px;text-align:center;}
.lz-eyebrow{font-size:12px;font-weight:800;letter-spacing:.22em;text-transform:uppercase;color:var(--green);display:block;margin-bottom:22px;}
.lz-hero h1{font-family:Poppins,sans-serif;font-weight:800;font-size:clamp(34px,6.4vw,58px);line-height:1.05;letter-spacing:-.03em;margin:0 0 20px;text-wrap:balance;color:var(--ink);}
.lz-grad{background:linear-gradient(100deg,var(--green2),#12A85E 45%,var(--gold));-webkit-background-clip:text;background-clip:text;color:transparent;}
.lz-sub{font-size:clamp(15px,2.2vw,18px);line-height:1.62;color:var(--ink2);max-width:600px;margin:0 auto 30px;}
.lz-ctas{display:flex;flex-direction:column;align-items:center;gap:11px;}
.lz-cta{position:relative;overflow:hidden;display:inline-flex;isolation:isolate;text-decoration:none;border-radius:15px;padding:2px;
  background:
    repeating-linear-gradient(57deg,rgba(255,220,120,.12) 0 1px,transparent 1px 8px),
    repeating-linear-gradient(123deg,rgba(255,220,120,.09) 0 1px,transparent 1px 8px),
    linear-gradient(165deg,#12A85E,#0B6B3E);
  box-shadow:0 6px 0 #064e2e,0 16px 36px rgba(12,122,70,.34);transition:transform .09s,filter .12s;}
/* The real GStyle rosette, not an approximation. Conic gradients were used
   here to keep the public page light, but the figure is overlapping petal
   loops — rays and rings never looked like it, and it read as a plain disc.
   One cached SVG shared with the app is the honest version. */
/* Masked, not drawn: the SVG's stroke colour is fixed, and masking lets the
   gold be chosen per surface. The right side of each button also darkens —
   in the app the rosette sits on a dark green card, which is the only reason
   thin gold lines read as gold. On flat bright #12A85E they have no contrast
   and come out as pale green scribble. */
.lz-cta::after,.lz-navcta::after,.lz-price-cta::after{content:"";position:absolute;z-index:-1;top:50%;pointer-events:none;background:#FFD24A;
  -webkit-mask-image:url(/gstyle-rosette.svg);-webkit-mask-size:contain;-webkit-mask-position:center;-webkit-mask-repeat:no-repeat;
  mask-image:url(/gstyle-rosette.svg);mask-size:contain;mask-position:center;mask-repeat:no-repeat;
  animation:lz-medallion 60s linear infinite;}
/* Far enough right that the rosette's hollow centre clears the edge — closer
   in, the centre reads as a dark smudge sitting on the button. */
.lz-cta::after,.lz-price-cta::after{right:-96px;width:158px;height:158px;margin-top:-79px;opacity:.6;}
.lz-navcta::after{right:-74px;width:112px;height:112px;margin-top:-56px;opacity:.5;}
.lz-cta{background:
    repeating-linear-gradient(57deg,rgba(255,220,120,.12) 0 1px,transparent 1px 8px),
    repeating-linear-gradient(123deg,rgba(255,220,120,.09) 0 1px,transparent 1px 8px),
    linear-gradient(100deg,#12A85E 38%,#0A6A3D 78%,#075530),
    linear-gradient(165deg,#12A85E,#0B6B3E);}
.lz-navcta{background:
    linear-gradient(100deg,#12A85E 58%,#0B7443 86%,#095F36),
    linear-gradient(165deg,#12A85E,#0B6B3E);}
@keyframes lz-medallion{to{transform:rotate(360deg)}}
/* Every green button on the page carries the same gold rule + rosette. */
.lz-navcta,.lz-price-cta{position:relative;isolation:isolate;overflow:hidden;}
.lz-navcta::before,.lz-price-cta::before{content:"";position:absolute;inset:4px;border:1px solid rgba(255,210,74,.42);
  border-radius:8px;pointer-events:none;}
.lz-price-cta::before{border-radius:9px;}
@media (prefers-reduced-motion:reduce){.lz-cta::after,.lz-navcta::after,.lz-price-cta::after{animation:none}}
.lz-cta::before{content:"";position:absolute;inset:6px;border:1px solid rgba(255,210,74,.45);border-radius:11px;pointer-events:none;z-index:1;}
.lz-cta:hover{filter:brightness(1.05)}
.lz-cta:active{transform:translateY(3px);box-shadow:0 3px 0 #064e2e,0 8px 18px rgba(12,122,70,.3)}
.lz-arr-w{display:inline-flex;align-items:center;gap:10px;font-family:Poppins,sans-serif;font-weight:800;font-size:16px;color:#fff;padding:15px 30px;}
.lz-arr{transition:transform .15s}
.lz-cta:hover .lz-arr{transform:translateX(3px)}
.lz-note{font-size:12.5px;color:var(--ink2);opacity:.85}
.lz-show-vid{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;display:block;}
.lz-feats{position:relative;}
.lz-show{position:relative;}
.lz-rose-feats{position:absolute;top:-70px;right:-120px;transform:scale(.75);opacity:.5;pointer-events:none;}
.lz-rose-show{position:absolute;bottom:-60px;left:-130px;transform:scale(.7);opacity:.5;pointer-events:none;}
.lz-card{display:flex;flex-direction:column;min-height:200px;}
.lz-card .lz-ic{font-size:30px;width:56px;height:56px;display:grid;place-items:center;}
.lz-heroshow{margin:40px auto 0;max-width:340px;position:relative;}
.lz-herorow{display:flex;align-items:center;justify-content:center;gap:26px;}
.lz-herovid{width:100%;max-width:340px;aspect-ratio:9/16;object-fit:cover;border-radius:22px;display:block;
  border:1px solid rgba(20,60,40,.18);box-shadow:0 24px 60px -18px rgba(15,55,35,.38),0 4px 14px rgba(15,55,35,.14);background:#0c120e;}
.lz-flank{display:none;width:236px;aspect-ratio:9/16;object-fit:cover;border-radius:18px;
  border:1px solid rgba(20,60,40,.14);box-shadow:0 18px 44px -16px rgba(15,55,35,.3),0 3px 10px rgba(15,55,35,.1);background:#0c120e;opacity:.96;}
@media (min-width:1024px){
  .lz-heroshow{max-width:960px;}
  .lz-flank{display:block;}
}
.lz-herotag{display:block;margin-top:12px;font-size:12px;font-weight:700;color:var(--ink2,#3d4340);opacity:.85;text-align:center;letter-spacing:.02em;}
.lz-footlinks{display:flex;gap:18px;flex-wrap:wrap;justify-content:center;margin-top:6px;}
.lz-footlinks a{font-size:12.5px;font-weight:700;color:var(--ink2,#3d4340);text-decoration:none;opacity:.75;}
.lz-footlinks a:hover{opacity:1;text-decoration:underline;}
@media (prefers-reduced-motion: reduce){.lz-herovid{display:none}.lz-flank{display:none}.lz-heroshow::after{content:"";display:block;aspect-ratio:9/16;border-radius:22px;background:url('/showcase/commercial-cover.jpg?v=2') center/cover;}}
.lz-stats{display:inline-flex;align-items:center;gap:24px;margin-top:42px;padding:16px 28px;border-radius:16px;
  background:linear-gradient(178deg,#FEFDF9,#F7F6EB);border:1px solid #D7DCCB;
  box-shadow:0 10px 30px rgba(20,32,26,.07),inset 0 1px 0 rgba(255,255,255,.85);}
.lz-stats>div{text-align:center}
.lz-stats b{display:block;font-family:Poppins,sans-serif;font-weight:800;font-size:26px;color:var(--green);line-height:1;}
.lz-stats span{font-size:11px;color:var(--ink2)}
.lz-div{width:1px;height:30px;background:var(--line)}
/* The AI trust strip. Quiet by design: wordmarks sit muted until hover so
   the strip reads as infrastructure, not advertising for someone else. */
.lz-powered{max-width:900px;margin:44px auto 0;padding:0 26px;text-align:center;}
.lz-autopost{max-width:900px;margin:40px auto 0;padding:0 26px;text-align:center;}
.lz-ap-points{list-style:none;display:flex;flex-wrap:wrap;justify-content:center;gap:8px 10px;margin:16px 0 0;padding:0;}
.lz-ap-points li{font-size:12.5px;font-weight:700;color:var(--ink2,#3d4340);border:1px solid var(--line,#e4e1d5);
  border-radius:999px;padding:7px 13px;background:rgba(255,255,255,.6);}
.lz-ap-points li::before{content:"✓";margin-right:7px;color:#1f7a4d;font-weight:900;}
.lz-pow-row{display:flex;flex-wrap:wrap;justify-content:center;gap:14px 34px;margin:18px 0 14px;}
.lz-pow{display:inline-flex;flex-direction:column;align-items:center;gap:4px;opacity:.62;filter:grayscale(1);transition:opacity .2s,filter .2s;}
.lz-pow:hover{opacity:1;filter:none;}
.lz-pow img{width:26px;height:26px;display:block;}
.lz-pow b{font-family:Poppins,sans-serif;font-weight:700;font-size:17px;letter-spacing:-.01em;color:var(--ink);}
.lz-pow i{font-style:normal;font-size:10.5px;letter-spacing:.14em;text-transform:uppercase;color:var(--muted);}
.lz-pow-note{max-width:560px;margin:0 auto;font-size:13.5px;line-height:1.55;color:var(--muted);}
@media(max-width:620px){.lz-pow-row{gap:12px 22px;}.lz-pow b{font-size:15px;}}
.lz-feats{max-width:1000px;margin:56px auto 0;padding:0 26px;display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:16px;}
.lz-card{background:linear-gradient(178deg,#FEFDF9,#F7F6EB);border:1px solid #D7DCCB;border-radius:18px;padding:22px 20px;
  box-shadow:0 3px 12px rgba(20,32,26,.06),inset 0 1px 0 rgba(255,255,255,.8);
  transition:transform .12s,border-color .12s,box-shadow .12s;}
.lz-card:hover{transform:translateY(-4px);border-color:var(--green2);box-shadow:0 16px 40px rgba(12,122,70,.14)}
.lz-ic{width:46px;height:46px;display:grid;place-items:center;font-size:23px;border-radius:13px;margin-bottom:14px;
  background:rgba(12,122,70,.09);box-shadow:inset 0 0 0 1px rgba(12,122,70,.2);}
.lz-card h3{font-family:Poppins,sans-serif;font-weight:700;font-size:16px;margin:0 0 7px;letter-spacing:-.01em;color:var(--ink);}
.lz-card p{font-size:13.5px;line-height:1.55;color:var(--ink2);margin:0;}
.lz-show,.lz-price,.lz-faq{max-width:1000px;margin:72px auto 0;padding:0 26px;text-align:center;}
.lz-show h2,.lz-price h2,.lz-faq h2{font-family:Poppins,sans-serif;font-weight:800;font-size:clamp(24px,4vw,34px);letter-spacing:-.02em;margin:10px 0 8px;color:var(--ink);text-wrap:balance;}
.lz-show-sub{font-size:15.5px;color:var(--ink2);margin:0 auto 28px;max-width:56ch;line-height:1.55;}
.lz-show-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:14px;}
.lz-show-card{position:relative;margin:0;aspect-ratio:3/4;background:#0F1512;border:1px solid #D7DCCB;border-radius:18px;overflow:hidden;box-shadow:0 3px 12px rgba(20,32,26,.06);transition:transform .12s,box-shadow .12s;}
.lz-show-card:hover{transform:translateY(-4px);box-shadow:0 16px 40px rgba(12,122,70,.14);}
.lz-show-img{position:absolute;inset:0;display:block;background-size:cover;background-position:center 20%;}
.lz-show-card figcaption{position:absolute;left:0;right:0;bottom:0;padding:30px 12px 11px;text-align:left;background:linear-gradient(180deg,rgba(8,12,10,0),rgba(8,12,10,.55) 40%,rgba(8,12,10,.86));}
.lz-show-card b{display:block;font-family:Poppins,sans-serif;font-size:13.5px;color:#fff;text-shadow:0 1px 2px rgba(0,0,0,.4);}
.lz-show-card span:not(.lz-show-img){font-size:11.5px;color:rgba(255,255,255,.88);line-height:1.4;display:block;text-shadow:0 1px 2px rgba(0,0,0,.4);}
.lz-price-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:18px;text-align:left;margin-top:26px;}
.lz-price-card{position:relative;background:linear-gradient(178deg,#FEFDF9,#F7F6EB);border:1px solid #D7DCCB;border-radius:20px;padding:26px 24px;
  box-shadow:0 3px 12px rgba(20,32,26,.06),inset 0 1px 0 rgba(255,255,255,.8);display:flex;flex-direction:column;}
.lz-price-card.feat{border-color:rgba(18,168,94,.55);box-shadow:0 18px 44px rgba(12,122,70,.16);}
.lz-price-ribbon{position:absolute;top:-11px;left:50%;transform:translateX(-50%);padding:4px 14px;border-radius:999px;font-family:Poppins,sans-serif;font-weight:800;font-size:11px;color:#fff;background:linear-gradient(165deg,#12A85E,#0B6B3E);box-shadow:0 4px 10px rgba(12,122,70,.3);}
.lz-price-name{font-family:Poppins,sans-serif;font-weight:800;font-size:18px;color:var(--ink);}
.lz-price-amt{font-family:Poppins,sans-serif;font-weight:800;font-size:38px;color:var(--green);margin-top:6px;}
.lz-price-amt small{font-size:15px;color:var(--ink2);font-weight:600;}
.lz-price-alt{font-size:12px;color:var(--ink2);margin-top:2px;}
.lz-price-tok{margin-top:14px;font-weight:700;font-size:13.5px;color:var(--gold-deep);}
.lz-price-cap{font-size:12.5px;color:var(--ink2);margin-top:3px;}
.lz-price-card ul{list-style:none;margin:16px 0 18px;padding:0;display:flex;flex-direction:column;gap:9px;flex:1;}
.lz-price-card li{position:relative;padding-left:24px;font-size:13.5px;line-height:1.45;color:var(--ink2);}
.lz-price-card li::before{content:"✓";position:absolute;left:2px;color:var(--green2);font-weight:900;}
.lz-price-cta{display:block;text-align:center;text-decoration:none;font-family:Poppins,sans-serif;font-weight:800;font-size:14px;color:#fff;padding:13px 18px;border-radius:13px;box-shadow:0 5px 14px rgba(12,122,70,.28);transition:filter .12s;
  background:linear-gradient(100deg,#12A85E 38%,#0A6A3D 78%,#075530),linear-gradient(165deg,#12A85E,#0B6B3E);}
.lz-price-cta:hover{filter:brightness(1.06);}
.lz-price-note{margin-top:20px;font-size:13px;color:var(--ink2);}
.lz-faq-list{max-width:660px;margin:26px auto 0;display:flex;flex-direction:column;gap:10px;text-align:left;}
.lz-faq details{background:linear-gradient(178deg,#FEFDF9,#F7F6EB);border:1px solid #D7DCCB;border-radius:14px;padding:15px 18px;
  box-shadow:0 2px 8px rgba(20,32,26,.05),inset 0 1px 0 rgba(255,255,255,.8);}
.lz-faq summary{cursor:pointer;font-family:Poppins,sans-serif;font-weight:700;font-size:14.5px;color:var(--ink);}
.lz-faq p{font-size:13.5px;line-height:1.6;color:var(--ink2);margin:10px 0 2px;}
.lz-compare{max-width:920px;margin:72px auto 0;padding:0 26px;text-align:center;}
.lz-vsname{color:var(--green2,#12A85E);}
.lz-compare h2{font-family:Poppins,sans-serif;font-weight:800;font-size:clamp(24px,4vw,34px);letter-spacing:-.02em;margin:10px 0 8px;color:var(--ink);text-wrap:balance;}
.lz-compare-sub{font-size:15.5px;color:var(--ink2);margin:0 auto 30px;max-width:52ch;line-height:1.55;}
.lz-vs{display:grid;grid-template-columns:1fr 1fr;gap:16px;text-align:left;}
.lz-vs-col{border-radius:18px;padding:24px 22px;}
.lz-vs-col.them{background:linear-gradient(178deg,#FEFDF9,#F7F6EB);border:1px solid #D7DCCB;box-shadow:0 3px 12px rgba(20,32,26,.06),inset 0 1px 0 rgba(255,255,255,.8);}
.lz-vs-col.us{position:relative;overflow:hidden;isolation:isolate;color:#EAF4EE;
  background:repeating-linear-gradient(57deg,rgba(255,214,102,.06) 0 1px,transparent 1px 7px),repeating-linear-gradient(123deg,rgba(255,214,102,.05) 0 1px,transparent 1px 7px),linear-gradient(160deg,#0E5233,#0A3421 58%,#062417);
  border:1px solid rgba(231,200,121,.34);box-shadow:0 18px 44px rgba(8,42,26,.32);}
.lz-vs-h{font-family:Poppins,sans-serif;font-weight:800;font-size:13px;letter-spacing:.08em;text-transform:uppercase;margin-bottom:14px;}
.lz-vs-col.them .lz-vs-h{color:var(--ink2);}
.lz-vs-col.us .lz-vs-h{color:var(--gold-hi,#E7C879);}
.lz-vs-col ul{list-style:none;margin:0;padding:0;display:flex;flex-direction:column;gap:11px;}
.lz-vs-col li{position:relative;padding-left:26px;font-size:14px;line-height:1.45;}
.lz-vs-col.them li{color:var(--ink2);}
.lz-vs-col.them li::before{content:"–";position:absolute;left:6px;color:#B0A98E;font-weight:800;}
.lz-vs-col.us li{color:#EAF4EE;}
.lz-vs-col.us li::before{content:"✓";position:absolute;left:2px;color:#7FE0AC;font-weight:900;}
@media(max-width:600px){.lz-vs{grid-template-columns:1fr}}
/* GStyle rosettes — the REAL engine-turned figure, the same hypotrochoid the
   embedded app spins, served as an asset. Conic gradients can only fake radial
   spokes; this shape is built from overlapping petal loops, and that is what
   makes it shimmer. Gold cut on the dark bands, green cut on cream where gold
   would simply vanish. */
.lz-rose{position:absolute;pointer-events:none;z-index:0;
  background:url(/gstyle-rosette.svg) center/contain no-repeat;
  animation:lz-medallion 44s linear infinite;}
/* isolation, or the hero rosette is invisible: .lz is position:relative with
   z-index:auto, so it makes no stacking context, and a z-index:-1 child of
   .lz-hero escapes all the way behind .lz's own background. */
.lz-hero{position:relative;isolation:isolate;}
/* The gold flower, front and centre of the hero — the mark people recognise
   from the app. It was the green cut parked so far off the right edge that a
   phone never saw it at all. */
.lz-rose-hero{right:-120px;top:-70px;width:440px;height:440px;opacity:.34;z-index:-1;}
@media(max-width:620px){.lz-rose-hero{right:-150px;top:-40px;width:400px;height:400px;opacity:.28;}}
.lz-rose-band{right:-110px;top:50%;width:430px;height:430px;margin-top:-215px;opacity:.3;}
.lz-rose-vs{right:-90px;bottom:-100px;width:310px;height:310px;opacity:.26;}
.lz-band-in>*{position:relative;z-index:1;}
.lz-band-in .lz-rose{z-index:0;}
.lz-vs-col.us>*{position:relative;z-index:1;}
.lz-vs-col.us .lz-rose{z-index:0;}
@media (prefers-reduced-motion:reduce){.lz-rose{animation:none}}
.lz-band{max-width:1000px;margin:64px auto 0;padding:0 26px;}
.lz-band-in{position:relative;isolation:isolate;overflow:hidden;text-align:center;border-radius:24px;padding:52px 32px;color:#EAF4EE;
  background:
    repeating-linear-gradient(57deg,rgba(255,214,102,.06) 0 1px,transparent 1px 7px),
    repeating-linear-gradient(123deg,rgba(255,214,102,.05) 0 1px,transparent 1px 7px),
    linear-gradient(160deg,#0E5233,#0A3421 55%,#072617);
  border:1px solid rgba(231,200,121,.34);box-shadow:0 24px 60px rgba(8,42,26,.4);}
.lz-band-in::before{content:"";position:absolute;inset:12px;border:1px solid rgba(255,210,74,.28);border-radius:16px;pointer-events:none;}
.lz-band-in h2{font-family:Poppins,sans-serif;font-weight:800;font-size:clamp(24px,4vw,34px);letter-spacing:-.02em;margin:0 0 12px;color:#F4EAC8;text-wrap:balance;}
.lz-band-in p{font-size:15.5px;color:rgba(220,240,225,.82);margin:0 auto 26px;max-width:480px;line-height:1.55;}
.lz-foot{max-width:1000px;margin:56px auto 0;padding:24px 26px 40px;display:flex;align-items:center;justify-content:space-between;
  border-top:1px solid var(--line);flex-wrap:wrap;gap:12px;}
.lz-copy{font-size:12.5px;color:var(--ink2);opacity:.8}
/* The mark: the raw tile is deep green and reads as a dark blob on cream, so
   it's set in a gold-rimmed crest and lifted — an emblem, not a smudge. */
.lz-crest{position:relative;flex:0 0 auto;display:inline-grid;place-items:center;border-radius:9px;overflow:hidden;
  border:1.5px solid rgba(199,158,63,.75);box-shadow:0 1px 3px rgba(20,32,26,.18),0 0 0 2px rgba(231,200,121,.16);}
.lz-crest img{width:100%;height:100%;object-fit:cover;display:block;image-rendering:pixelated;filter:brightness(1.16) saturate(1.06);}
.lz-crest::after{content:"";position:absolute;inset:0;border-radius:inherit;pointer-events:none;
  background:linear-gradient(150deg,rgba(255,255,255,.24),transparent 52%);}
@media(max-width:820px){.lz-feats{grid-template-columns:1fr 1fr}}
@media(max-width:520px){.lz-feats{grid-template-columns:1fr}.lz-stats{gap:16px;padding:14px 18px}.lz-stats b{font-size:22px}}
/* ---- Mobile header: four controls on one 390px row is a scrum. The globe
        collapses to the flag-less select, Log in becomes a real bordered
        target, and Start free stays the one loud thing in the bar. ---- */
@media(max-width:620px){
  .lz-nav{padding:14px 16px;gap:8px;}
  .lz-brand{font-size:16px;gap:7px;}
  .lz-lang{font-size:12px;gap:3px;}
  .lz-lang select{padding:7px 6px;font-size:12px;max-width:78px;}
  .lz-navlink{font-weight:800;font-size:12.5px;color:var(--ink);padding:9px 13px;border-radius:11px;
    background:var(--card);border:1px solid var(--line);box-shadow:0 2px 6px rgba(20,32,26,.06);}
  .lz-navcta{font-size:12.5px;padding:10px 15px;}
  .lz-hero{padding:34px 18px 24px;}
  .lz-foot{padding:22px 18px 34px;}
}
/* Phone widths: the wordmark stays — it's the brand. The language select
   gives up its width instead, and the two buttons tighten. */
@media(max-width:430px){
  .lz-nav{gap:6px;padding:12px 12px;}
  .lz-brand{font-size:15px;gap:6px;}
  .lz-lang{font-size:0;gap:0;}
  .lz-lang select{max-width:54px;padding:7px 3px;font-size:11.5px;}
  .lz-navlink{padding:9px 10px;font-size:12px;}
  .lz-navcta{padding:9px 12px;font-size:12px;}
}
`;
